mnist:
  datasets_paths:
    training: "C:/Users/avolk/Downloads/mnist/mnist_training_set.json"
    validation: "C:/Users/avolk/Downloads/mnist/mnist_validation_set.json"
    test: "C:/Users/avolk/Downloads/mnist/mnist_test_set.json"

mnist_sequence:
  datasets_paths:
    training: "<PATH>/<FILENAME>.jsonl"
    validation: "<PATH>/<FILENAME>.jsonl"
    test: "<PATH>/<FILENAME>.jsonl"

sparse_input:
  datasets_paths:
    training: "<PATH>/<FILENAME>.jsonl"
    validation: "<PATH>/<FILENAME>.jsonl"
    test: "<PATH>/<FILENAME>.jsonl"

progressive_sum:
  datasets_paths:
    training: "<PATH>/<FILENAME>.jsonl"
    validation: "<PATH>/<FILENAME>.jsonl"
    test: "<PATH>/<FILENAME>.jsonl"

han_classifier:
  datasets_paths:
    training: "<PATH>/<FILENAME>.jsonl"
    validation: "<PATH>/<FILENAME>.jsonl"
    test: "<PATH>/<FILENAME>.jsonl"

vectors_average:
  datasets_paths:
    training:  "<PATH>/<FILENAME>.csv"
    validation: ""
    test: ""